export const BaseURL = "http://localhost:8081"
export const CreateAccountPageLink = "/CreateAccount"
export const ManageSessionPageLink = "/ManageSession"
export const AccCreate = "/accounts/createAccount"
export const ChangeBool = "/accounts/changeBool"
export const PathToGetAccount = "/accounts/getAccountById/{id}"