// Local
// export const BaseURL = "http://localhost:8081"
// export const BaseURL = "http://35.189.117.216:8081"
// k8s
export const BaseURL = ""
export const CreateAccountPageLink = "/register"
export const ManageSessionPageLink = "/session"
export const AccCreate = "/accounts/createAccount"
export const ChangeBool = "/accounts/changeBool"
export const PathToGetAccount = "/accounts/getAccountById/"
export const getAccounts = "/getAccounts"
export const accounts = "/accounts"
export const updateAccount = "/updateAccountById/{id}"
export const getPlayers = "/getPlaying" 
export const changeBool = "/changeBool/"
export const qaTrainee = "@academytrainee.com"
export const qaStaff = "@qa.com"
